name: mbank

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    environment:
      - REDIS_ARGS="--requirepass cantremember"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
